name: mobile
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.4.0
  shared_preferences: ^2.2.3
  image_picker: ^1.1.2
  geolocator: ^13.0.0
  url_launcher: ^6.3.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.9
  qr_flutter: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/loginIcon.svg
    - assets/images/loginIcon2.svg
    - assets/images/loginIcon3.svg
    - assets/images/backgroundLogo.svg
    - assets/images/cardDesign.svg
    - assets/images/healio.svg
    - assets/images/healio.png
    - assets/images/QrBackground.svg 
    - assets/images/IdBackground.svg  
    - assets/images/upBlur.svg
    - assets/icons/home.svg
    - assets/icons/calendar.svg
    - assets/icons/chat.svg
    - assets/icons/card.svg
    - assets/icons/dossier.svg
    - assets/icons/profile.svg
    - assets/icons/star.svg
    - assets/icons/message.svg
    - assets/icons/ai.svg
    - assets/icons/file.svg

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/healio.png"
  min_sdk_android: 21