// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvL089hdkogsdadiSs9KisjFuJq-nUjOk',
    appId: '1:645675223824:web:3a077686002f216225f395',
    messagingSenderId: '645675223824',
    projectId: 'medical-project-2cp',
    authDomain: 'medical-project-2cp.firebaseapp.com',
    storageBucket: 'medical-project-2cp.firebasestorage.app',
    measurementId: 'G-ECV8XF360F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC52sZ8QZPgyhjWX2OeWLTzzCqW6HHfYO0',
    appId: '1:645675223824:android:d13dff0423657afc25f395',
    messagingSenderId: '645675223824',
    projectId: 'medical-project-2cp',
    storageBucket: 'medical-project-2cp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGjkHxLYD9eL1GTBVYmKnP6Q30hjMG6aE',
    appId: '1:645675223824:ios:e4110435d67834fc25f395',
    messagingSenderId: '645675223824',
    projectId: 'medical-project-2cp',
    storageBucket: 'medical-project-2cp.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGjkHxLYD9eL1GTBVYmKnP6Q30hjMG6aE',
    appId: '1:645675223824:ios:e4110435d67834fc25f395',
    messagingSenderId: '645675223824',
    projectId: 'medical-project-2cp',
    storageBucket: 'medical-project-2cp.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvL089hdkogsdadiSs9KisjFuJq-nUjOk',
    appId: '1:645675223824:web:d83e1c2afa63904825f395',
    messagingSenderId: '645675223824',
    projectId: 'medical-project-2cp',
    authDomain: 'medical-project-2cp.firebaseapp.com',
    storageBucket: 'medical-project-2cp.firebasestorage.app',
    measurementId: 'G-XG9Z8JP64F',
  );
}
